name: Test React App
on: push
jobs:
  test:
    runs-on: ubuntu_latest
    steps:
      - name: To get the repository code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Test application
        run: npm run test